### ISSUE TITLE
Where are the config files stored?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/archivebox_ynh#10]
The developers recommend some stuff that I do to my instance, here https://github.com/ArchiveBox/ArchiveBox/issues/844 , but I cannot find the proper config file. Where is it located? Thanks!

**Comment by mhfowler** [comment]
hi @tio-trom, sorry I missed this issue until now. 

The config file should be at 
`/home/yunohost.app/YOURAPPNAME/ArchiveBox.conf`

most likely, 
`/home/yunohost.app/archivebox/ArchiveBox.conf`

After editing the config file, you can restart archivebox with 
`systemctl restart YOURAPPNAME`
