### ISSUE TITLE
Archivebox fails to install on yunohost 4.2.8

### ISSUE THREAD

**Issue by czen** [YunoHost-Apps/archivebox_ynh#2]
### Describe the bug

*App fails to install on yunohost 4.2.8 inside virtual machine.*

### Context

- Hardware: *Virtualbox with latest Yunohost installed from the iso downloaded from the official site*
- YunoHost version: 4.2.8

### Steps to reproduce

- download yunohst ISO
- setup new virtual machine
- setup a domain
- try installing Archivebox through cli or web interface

### Logs

https://paste.yunohost.org/raw/xunuzizigo

**Comment by mhfowler** [comment]
thanks @czen , I will let you know when its fixed, hopefully in next few days

**Comment by mhfowler** [comment]
@czen the issue should now be fixed. please let me know if you get a chance to try it

**Comment by czen** [comment]
Thanks, now it installs and works.
