### ISSUE TITLE
Application requires CPU supporting SSE3

### ISSUE THREAD

**Issue by tepiloxtl** [YunoHost-Apps/archivebox_ynh#22]
### Describe the bug

Installation fails because this package depends on Chromium, which depends on CPU supporting SSE3 (depends on package sse3-support)

### Context

- Hardware: Old PC - HP T510
- YunoHost version: 11.0.7 (testing)
- I have access to my server: *Through SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Hardware requires nonfree kernel modules and specific load order to work, edited modprobe blacklists/whitelists to reflect that
- Using, or trying to install package version/branch: 0.6.2~ynh9 (from the panel)

### Steps to reproduce

Begin installation process of ArchiveBox through panel or ssh

### Expected behavior

It should be mentioned in the Readme file that this application requires SSE3. Alternatively, allow option of installing this application without Chromium (it seems to not be a required dependency, although ArchiveBox would work with degraded functionality when its missing)

### Logs

https://paste.yunohost.org/raw/unatakomah

**Comment by yalh76** [comment]
> ### Expected behavior
> 
> It should be mentioned in the Readme file that this application requires SSE3. Alternatively, allow option of installing this application without Chromium (it seems to not be a required dependency, although ArchiveBox would work with degraded functionality when its missing)

Requirement for SSE3 added in the readme
For chromium do you think it's better not to have screenshots, PDF, and DOM dump output like written at https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#dependency-options ?
