### ISSUE TITLE
Settings don't seem to work

### ISSUE THREAD

**Issue by C-Loftus** [YunoHost-Apps/archivebox_ynh#24]
Settings in this `ArchiveBox.conf` file don't seem to persist, any ideas why? I have done `systemctl restart archivebox` as well after changing settings. I am trying to disable `archive_org` so I can archive personal info.
```
$ pwd
/etc/yunohost/apps/archivebox
$ cd
cd conf/
$ ls
ArchiveBox.conf  nginx.conf  package.json  package-lock.json  requirements.txt  start.sh  systemd.service
$ cat ArchiveBox.conf
[DEPENDENCY_CONFIG]
NODE_BINARY=__YNH_NODE__
[ARCHIVE_METHOD_TOGGLES]
SAVE_ARCHIVE_DOT_ORG = False

$ systemctl restart archivebox
```
This doesn't work even though I get no errors.
I have also tried settting `SAVE_ARCHIVE_DOT_ORG = False` as its own line not within the `[ARCHIVE_METHOD_TOGGLES]` group.

**Comment by yalh76** [comment]
It's because the good `ArchiveBox.conf` is at `/home/yunohost.app/archivebox/ArchiveBox.conf`
