### ISSUE TITLE
Strange version of shipped package

### ISSUE THREAD

**Issue by dumprop** [YunoHost-Apps/archivebox_ynh#7]
Normally first part means package version and second part means ynh script's version
![image](https://user-images.githubusercontent.com/34004367/132947390-0e7c2852-a7a8-4e53-895c-b9851b4497ae.png)
But the latest version of package is 0.6.2
![image](https://user-images.githubusercontent.com/34004367/132947398-b2a9576f-637b-4ec0-bdc3-4193d539813a.png)
So, expected something like 0.6.2~ynh7

**Comment by mhfowler** [comment]
thanks @dumprop for the tip, appreciated 

closed https://github.com/YunoHost-Apps/archivebox_ynh/pull/8/
